2020-10-19 16:50:09,737 ERROR 13356 [-/192.168.3.150/-/355ms GET /getsearch?state=18212418574] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'phone' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\12552\Desktop\dada\serve\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\12552\Desktop\dada\serve\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\12552\Desktop\dada\serve\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\12552\Desktop\dada\serve\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\12552\Desktop\dada\serve\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\12552\Desktop\dada\serve\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\12552\Desktop\dada\serve\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\12552\Desktop\dada\serve\node_modules\_co@4.6.0@co\index.js:54:5
    sql: select * from myorder where phone="18212418574"
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'phone' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select * from myorder where phone=\"18212418574\""
headers: {"Access-Control-Allow-Origin":"http://192.168.3.150:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 13356
hostname: DESKTOP-K5ULKD4

